import { Inter, Oswald,Urbanist } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { Providers } from "../../store/provider";


const urbanist = Urbanist({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={urbanist.className}>
      <Header/>
      <Providers>

      {children}
      </Providers>
      <Footer/>
      </body>
    </html>
  );
}
